# Generated by Django 6.1 on 2026-08-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0002_uudp_compliance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consentrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="consentauditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="consentauditlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("learning", "Learning Data Processing"),
                    ("analytics", "Aggregate Analytics"),
                    ("communication", "Communication"),
                    ("third_party", "Third Party Sharing"),
                    ("marketing", "Marketing & Promotions"),
                    ("child_data", "Child Personal Data Processing"),
                    ("safeguarding", "Safeguarding & Welfare"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datadeletionrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="dataexportrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
