# Generated by Django 6.1 on 2026-08-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_preferences_queue"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationqueue",
            new_name="notificatio_status_dcd7ee_idx",
            old_name="notif_queue_status_idx",
        ),
        migrations.AlterField(
            model_name="notificationqueue",
            name="channel",
            field=models.CharField(
                choices=[
                    ("in_app", "In App"),
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=20,
            ),
        ),
    ]
