# Generated by Django 6.1 on 2026-08-21 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("multiple_select", "Multiple Select"),
                            ("true_false", "True/False"),
                            ("image_hotspot", "Image Hotspot"),
                            ("drag_and_drop", "Drag and Drop"),
                            ("interactive_video", "Interactive Video"),
                            ("essay", "Essay"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("grading", models.JSONField(blank=True, default=dict)),
                ("accessibility", models.JSONField(blank=True, default=dict)),
                ("learning_objectives", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_definitions",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "activity_definitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("settings", models.JSONField(default=dict)),
                ("grading", models.JSONField(default=dict)),
                ("checksum", models.CharField(max_length=64)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="activities.activitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "activity_versions",
                "ordering": ["-version_number"],
                "unique_together": {("definition", "version_number")},
            },
        ),
    ]
