# Generated by Django 6.1 on 2026-08-21 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitydefinition",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_definitions",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum number of attempts allowed"
            ),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="pass_mark_percentage",
            field=models.PositiveIntegerField(
                default=50, help_text="Percentage needed to pass"
            ),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="show_correct_answers",
            field=models.BooleanField(
                default=True, help_text="Show correct answers after submission"
            ),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="shuffle_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitydefinition",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time limit in minutes, null = unlimited",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ActivityQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("multiple_select", "Multiple Select"),
                            ("true_false", "True/False"),
                            ("image_hotspot", "Image Hotspot"),
                            ("drag_and_drop", "Drag and Drop"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("prompt", models.TextField(help_text="Question text or prompt")),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text='List of option objects: [{"id": "a", "text": "...", "image_url": "..."}]',
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        help_text="Correct answer value: string for MC/TF, list of strings for MS/DnD"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation shown after submission",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="activities.activitydefinition",
                    ),
                ),
            ],
            options={
                "db_table": "activity_questions",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
