# Generated by Django 6.1 on 2026-08-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_player_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitydefinition",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("multiple_select", "Multiple Select"),
                    ("true_false", "True/False"),
                    ("image_hotspot", "Image Hotspot"),
                    ("drag_and_drop", "Drag and Drop"),
                    ("interactive_video", "Interactive Video"),
                    ("branching_scenario", "Branching Scenario"),
                    ("essay", "Essay"),
                ],
                max_length=30,
            ),
        ),
    ]
