# Generated by Django 6.1 on 2026-08-21 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("interactive", "Interactive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, default="", max_length=500)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
