# Generated by Django 6.1 on 2026-08-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_items",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
