# Generated by Django 6.1 on 2026-08-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_player_v2"),
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="response",
            name="question_id",
        ),
        migrations.AddField(
            model_name="attempt",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="activities.activitydefinition",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="attempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="letter_grade",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="attempt",
            name="passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="max_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="activities.activityquestion",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="activity_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="activities.activityversion",
            ),
        ),
    ]
