# Generated by Django 6.1 on 2026-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="face_thumbnail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Base64-encoded JPEG thumbnail (≤100×100 px, ≤50 KB).",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="location_accuracy_m",
            field=models.FloatField(
                blank=True,
                help_text="GPS accuracy in metres at check-in time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="self_checked",
            field=models.BooleanField(
                default=False,
                help_text="True if the student checked in themselves (vs instructor roll).",
            ),
        ),
    ]
