# Generated by Django 6.1 on 2026-09-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="YouTube or Google Drive embed URL for a video brief",
                max_length=500,
            ),
        ),
    ]
