# Generated by Django 6.1 on 2026-09-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_exam_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("file", "File / Text Submission"),
                    ("mcq", "Multiple Choice Quiz"),
                    ("essay", "Essay Task"),
                    ("combined", "Combined (MCQ + Essay)"),
                    ("exam", "Exam (PDF Paper + Answer Sheet)"),
                ],
                default="file",
                help_text="What kind of task this is: file/text submission, MCQ quiz, essay task, or a combination.",
                max_length=20,
            ),
        ),
    ]
