# Generated by Django 6.1 on 2026-08-22 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("va_bca", "Virtual Account BCA"),
                            ("va_bni", "Virtual Account BNI"),
                            ("va_bri", "Virtual Account BRI"),
                            ("va_mandiri", "Virtual Account Mandiri"),
                            ("va_permata", "Virtual Account Permata"),
                            ("gopay", "GoPay"),
                            ("ovo", "OVO"),
                            ("dana", "DANA"),
                            ("shopeepay", "ShopeePay"),
                            ("qris", "QRIS"),
                            ("credit_card", "Credit Card"),
                            ("indomaret", "Indomaret"),
                            ("alfamart", "Alfamart"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "midtrans_order_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("midtrans_token", models.TextField(blank=True, default="")),
                (
                    "midtrans_redirect_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "midtrans_fraud_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="finance.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_intents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settlement", "Settlement"),
                            ("capture", "Capture"),
                            ("deny", "Deny"),
                            ("challenge", "Challenge"),
                            ("cancel", "Cancel"),
                            ("expire", "Expire"),
                            ("refund", "Refund"),
                            ("partial_refund", "Partial Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "midtrans_status_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("midtrans_status_message", models.TextField(blank=True, default="")),
                (
                    "midtrans_transaction_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "midtrans_transaction_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "midtrans_settlement_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "midtrans_payment_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "midtrans_fraud_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("webhook_received_at", models.DateTimeField(auto_now_add=True)),
                ("webhook_raw", models.JSONField(blank=True, default=dict)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "midtrans_refund_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "midtrans_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="finance.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_refunds",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["invoice", "status"], name="payment_int_invoice_2e2865_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["midtrans_order_id"], name="payment_int_midtran_b002b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["midtrans_transaction_id"],
                name="payment_tra_midtran_62c753_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_intent", "status"],
                name="payment_tra_payment_38ef0c_idx",
            ),
        ),
    ]
