# Generated by Django 6.1 on 2026-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="midtrans_settlement_time",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="midtrans_transaction_time",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
