# Generated by Django 6.1 on 2026-08-21 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("page_width", models.PositiveIntegerField(default=1240)),
                ("page_height", models.PositiveIntegerField(default=1754)),
                ("pages", models.JSONField(blank=True, default=list)),
                ("layers", models.JSONField(blank=True, default=list)),
                ("document_version", models.PositiveIntegerField(default=1)),
                (
                    "submitted_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                (
                    "attempt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvas_documents",
                        to="attempts.attempt",
                    ),
                ),
            ],
            options={
                "db_table": "canvas_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
