# Generated by Django 6.1 on 2026-08-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0002_4layer_canvas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canvasdocument",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="canvasdocument",
            name="layers",
        ),
        migrations.RemoveField(
            model_name="canvasdocument",
            name="pages",
        ),
    ]
