# Generated by Django 6.1 on 2026-08-21 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("essays", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="essayquestion",
            name="allow_canvas_response",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="allow_file_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="allow_typed_response",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essay_questions",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="expected_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="late_penalty_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="late_submission_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="learning_objectives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="essay_questions",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="max_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EssayResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("typed_answer", models.TextField(blank=True, default="")),
                ("canvas_data", models.JSONField(blank=True, default=dict)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("locked", "Locked"),
                            ("grading", "Grading"),
                            ("returned", "Returned"),
                            ("resubmitted", "Resubmitted"),
                            ("finalised", "Finalised"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("overall_feedback", models.TextField(blank=True, default="")),
                ("feedback_released", models.BooleanField(default=False)),
                ("feedback_released_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True, default="")),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_essays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="essays.essayquestion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "essay_responses",
                "ordering": ["-submitted_at", "-created_at"],
                "unique_together": {("question", "student", "version")},
            },
        ),
        migrations.CreateModel(
            name="InlineFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Position"),
                            ("canvas", "Canvas Position"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("text_start", models.PositiveIntegerField(blank=True, null=True)),
                ("text_end", models.PositiveIntegerField(blank=True, null=True)),
                ("selected_text", models.TextField(blank=True, default="")),
                ("canvas_x", models.FloatField(blank=True, null=True)),
                ("canvas_y", models.FloatField(blank=True, null=True)),
                ("canvas_width", models.FloatField(blank=True, null=True)),
                ("canvas_height", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField()),
                ("is_visible_to_student", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inline_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_feedbacks",
                        to="essays.essayresponse",
                    ),
                ),
            ],
            options={
                "db_table": "inline_feedbacks",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_criteria",
                        to="essays.essayquestion",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_criteria",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="essays.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_levels",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="RubricScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="essays.rubriccriterion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_scores",
                        to="essays.essayresponse",
                    ),
                ),
                (
                    "scored_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rubric_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rubric_scores",
                "unique_together": {("response", "criterion")},
            },
        ),
    ]
