# Generated by Django 6.1 on 2026-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essays", "0002_essayquestion_allow_canvas_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayquestion",
            name="video_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
