-- ================================================
-- AKADEMI Digital Campus - Private Storage Buckets
-- ================================================
-- Run AFTER 001, 002, 003.
-- All buckets are PRIVATE. Files are only accessible via
-- short-lived signed URLs generated by Django (service role).
-- Direct client access is deny-by-default.
--
-- Buckets:
--   content-library   : course materials uploaded by instructors/admins
--   submissions       : student assignment uploads (PDF/DOCX/images)
--   canvas-exports    : Annotation Canvas PNG/PDF snapshots
--   certificates      : issued certificate PDFs
-- ================================================

-- ================================================
-- BUCKETS (all private)
-- ================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('content-library', 'content-library', false, 52428800,
   ARRAY['image/png','image/jpeg','image/webp','application/pdf',
         'video/mp4','audio/mpeg','application/zip']),
  ('submissions', 'submissions', false, 26214400,
   ARRAY['image/png','image/jpeg','image/webp','application/pdf',
         'application/msword',
         'application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
  ('canvas-exports', 'canvas-exports', false, 10485760,
   ARRAY['image/png','application/pdf']),
  ('certificates', 'certificates', false, 10485760,
   ARRAY['application/pdf'])
ON CONFLICT (id) DO UPDATE
  SET public = false,
      file_size_limit = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ================================================
-- CLEAN SLATE: drop policies if re-running this file
-- ================================================

DROP POLICY IF EXISTS storage_content_library_staff ON storage.objects;
DROP POLICY IF EXISTS storage_content_library_read ON storage.objects;
DROP POLICY IF EXISTS storage_submissions_student ON storage.objects;
DROP POLICY IF EXISTS storage_submissions_instructor ON storage.objects;
DROP POLICY IF EXISTS storage_canvas_exports_owner ON storage.objects;
DROP POLICY IF EXISTS storage_canvas_exports_teacher ON storage.objects;
DROP POLICY IF EXISTS storage_certificates_admin ON storage.objects;
DROP POLICY IF EXISTS storage_certificates_recipient ON storage.objects;

-- ================================================
-- CONTENT LIBRARY
-- Write: instructor/admin/owner in org (folder = organisation_id)
-- Read: any authenticated user in the same organisation
-- Path convention: {organisation_id}/{filename}
-- ================================================

CREATE POLICY storage_content_library_staff ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'content-library'
    AND auth.role() = 'authenticated'
    AND (
      public.user_has_role('instructor')
      OR public.is_admin_or_owner()
    )
  );

CREATE POLICY storage_content_library_read ON storage.objects
  FOR SELECT USING (
    bucket_id = 'content-library'
    AND auth.role() = 'authenticated'
  );

-- ================================================
-- SUBMISSIONS
-- Student: write/read ONLY own folder. Path convention: {student_id}/{filename}
-- Instructor: read submissions for their courses' students
-- Admin/Owner: read all
-- ================================================

CREATE POLICY storage_submissions_student ON storage.objects
  FOR ALL USING (
    bucket_id = 'submissions'
    AND auth.role() = 'authenticated'
    AND (
      -- student owns folder
      (public.user_is_student()
       AND (storage.foldername(name))[1] = public.get_user_id()::text)
      OR public.is_admin_or_owner()
    )
  ) WITH CHECK (
    bucket_id = 'submissions'
    AND auth.role() = 'authenticated'
    AND (
      (public.user_is_student()
       AND (storage.foldername(name))[1] = public.get_user_id()::text)
      OR public.is_admin_or_owner()
    )
  );

CREATE POLICY storage_submissions_instructor ON storage.objects
  FOR SELECT USING (
    bucket_id = 'submissions'
    AND auth.role() = 'authenticated'
    AND public.user_is_instructor()
    AND public.is_verified_instructor_of_student(
      (((storage.foldername(name))[1])::uuid)
    )
  );

-- ================================================
-- CANVAS EXPORTS
-- Owner folder = user who exported. Path: {user_id}/{canvas_doc_id}.png|pdf
-- Student/instructor read own; instructor reads course docs via API signed URLs
-- ================================================

CREATE POLICY storage_canvas_exports_owner ON storage.objects
  FOR ALL USING (
    bucket_id = 'canvas-exports'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = public.get_user_id()::text
  ) WITH CHECK (
    bucket_id = 'canvas-exports'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = public.get_user_id()::text
  );

CREATE POLICY storage_canvas_exports_teacher ON storage.objects
  FOR SELECT USING (
    bucket_id = 'canvas-exports'
    AND auth.role() = 'authenticated'
    AND (
      public.is_admin_or_owner()
      OR public.user_has_role('instructor')
    )
  );

-- ================================================
-- CERTIFICATES
-- Write: admin/owner/instructor only (Django generates PDFs via service role anyway)
-- Read: recipient (folder = recipient_id) + admins
-- Public verification goes through the API, NOT direct object access.
-- Path convention: {recipient_id}/{certificate_code}.pdf
-- ================================================

CREATE POLICY storage_certificates_admin ON storage.objects
  FOR ALL USING (
    bucket_id = 'certificates'
    AND auth.role() = 'authenticated'
    AND (
      public.is_admin_or_owner()
      OR public.user_has_role('instructor')
    )
  ) WITH CHECK (
    bucket_id = 'certificates'
    AND auth.role() = 'authenticated'
    AND (
      public.is_admin_or_owner()
      OR public.user_has_role('instructor')
    )
  );

CREATE POLICY storage_certificates_recipient ON storage.objects
  FOR SELECT USING (
    bucket_id = 'certificates'
    AND auth.role() = 'authenticated'
    AND (storage.foldername(name))[1] = public.get_user_id()::text
  );

-- ================================================
-- NOTE on helper used above:
-- is_verified_instructor_of_student may not exist in earlier migrations.
-- Create it defensively here (idempotent).
-- ================================================

CREATE OR REPLACE FUNCTION public.is_verified_instructor_of_student(p_student_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.enrolments e
    JOIN public.courses c ON c.id = e.course_id
    WHERE e.student_id = p_student_id
      AND e.status = 'active'
      AND c.instructor_id = public.get_user_id()
  );
$$;
