# Generated by Django 6.1 on 2026-08-21 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_id", models.UUIDField(db_index=True)),
                ("actor_email", models.EmailField(max_length=254)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_event_action_263795_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_event_resourc_917803_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"],
                        name="audit_event_actor_i_e566c4_idx",
                    ),
                ],
            },
        ),
    ]
