# Generated by Django 6.1 on 2026-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["block_index"]},
        ),
        migrations.AddField(
            model_name="certificate",
            name="block_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of this certificate block",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="block_index",
            field=models.PositiveIntegerField(
                default=0, help_text="Sequential index in the blockchain"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash of the previous certificate in the chain",
                max_length=64,
            ),
        ),
    ]
